# Form implementation generated from reading ui file 'products.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_List_of_products(object):
    def setupUi(self, List_of_products):
        List_of_products.setObjectName("List_of_products")
        List_of_products.resize(1123, 645)
        List_of_products.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(parent=List_of_products)
        self.centralwidget.setObjectName("centralwidget")
        self.logo_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(10, 10, 71, 61))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("../import/Icon.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 0, 921, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.provider_input = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.provider_input.setFont(font)
        self.provider_input.setStyleSheet("#provider_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#provider_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.provider_input.setObjectName("provider_input")
        self.provider_input.addItem("")
        self.horizontalLayout_3.addWidget(self.provider_input)
        self.sort_input = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sort_input.setFont(font)
        self.sort_input.setStyleSheet("#sort_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#sort_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.sort_input.setObjectName("sort_input")
        self.sort_input.addItem("")
        self.sort_input.addItem("")
        self.sort_input.addItem("")
        self.horizontalLayout_3.addWidget(self.sort_input)
        self.search_input = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.search_input.setFont(font)
        self.search_input.setStyleSheet("#search_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#search_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.search_input.setText("")
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_3.addWidget(self.search_input)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.add_product_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.add_product_button.setMinimumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.add_product_button.setFont(font)
        self.add_product_button.setStyleSheet("#add_product_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#add_product_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.add_product_button.setObjectName("add_product_button")
        self.horizontalLayout_10.addWidget(self.add_product_button)
        self.delete_product_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.delete_product_button.setMinimumSize(QtCore.QSize(85, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.delete_product_button.setFont(font)
        self.delete_product_button.setStyleSheet("#delete_product_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#delete_product_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.delete_product_button.setObjectName("delete_product_button")
        self.horizontalLayout_10.addWidget(self.delete_product_button)
        self.order_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.order_button.setMinimumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.order_button.setFont(font)
        self.order_button.setStyleSheet("#order_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#order_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.order_button.setObjectName("order_button")
        self.horizontalLayout_10.addWidget(self.order_button)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_fio = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.user_fio.setFont(font)
        self.user_fio.setObjectName("user_fio")
        self.horizontalLayout.addWidget(self.user_fio)
        self.logout_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.logout_button.setMinimumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("#logout_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#logout_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout.addWidget(self.logout_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(90, 90, 941, 471))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 922, 716))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_7 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_7.setMinimumSize(QtCore.QSize(900, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(801, 171))
        self.widget_7.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.photo_10 = QtWidgets.QLabel(parent=self.widget_7)
        self.photo_10.setMaximumSize(QtCore.QSize(150, 150))
        self.photo_10.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.photo_10.setText("")
        self.photo_10.setPixmap(QtGui.QPixmap("../import/1.jpg"))
        self.photo_10.setScaledContents(True)
        self.photo_10.setObjectName("photo_10")
        self.horizontalLayout_11.addWidget(self.photo_10)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_18.addWidget(self.label_15)
        self.label_27 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_18.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_18.addWidget(self.label_28)
        self.label_46 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_46.setObjectName("label_46")
        self.verticalLayout_18.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_47.setObjectName("label_47")
        self.verticalLayout_18.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_48.setObjectName("label_48")
        self.verticalLayout_18.addWidget(self.label_48)
        self.verticalLayout_5.addLayout(self.verticalLayout_18)
        self.horizontalLayout_11.addWidget(self.widget_8)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.sale_11 = QtWidgets.QLabel(parent=self.widget_7)
        self.sale_11.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sale_11.setFont(font)
        self.sale_11.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.sale_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sale_11.setObjectName("sale_11")
        self.horizontalLayout_9.addWidget(self.sale_11)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(900, 0))
        self.widget.setMaximumSize(QtCore.QSize(801, 171))
        self.widget.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.photo_7 = QtWidgets.QLabel(parent=self.widget)
        self.photo_7.setMaximumSize(QtCore.QSize(150, 150))
        self.photo_7.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.photo_7.setText("")
        self.photo_7.setPixmap(QtGui.QPixmap("../import/1.jpg"))
        self.photo_7.setScaledContents(True)
        self.photo_7.setObjectName("photo_7")
        self.horizontalLayout_2.addWidget(self.photo_7)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.label_21 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_15.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_15.addWidget(self.label_22)
        self.label_37 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_37.setObjectName("label_37")
        self.verticalLayout_15.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_15.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_39.setObjectName("label_39")
        self.verticalLayout_15.addWidget(self.label_39)
        self.verticalLayout.addLayout(self.verticalLayout_15)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.sale_8 = QtWidgets.QLabel(parent=self.widget)
        self.sale_8.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sale_8.setFont(font)
        self.sale_8.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.sale_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sale_8.setObjectName("sale_8")
        self.horizontalLayout_4.addWidget(self.sale_8)
        self.verticalLayout_4.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_3.setMinimumSize(QtCore.QSize(900, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(801, 171))
        self.widget_3.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.photo_8 = QtWidgets.QLabel(parent=self.widget_3)
        self.photo_8.setMaximumSize(QtCore.QSize(150, 150))
        self.photo_8.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.photo_8.setText("")
        self.photo_8.setPixmap(QtGui.QPixmap("../import/1.jpg"))
        self.photo_8.setScaledContents(True)
        self.photo_8.setObjectName("photo_8")
        self.horizontalLayout_6.addWidget(self.photo_8)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.label_23 = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_16.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_16.addWidget(self.label_24)
        self.label_40 = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_16.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_16.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_42.setObjectName("label_42")
        self.verticalLayout_16.addWidget(self.label_42)
        self.verticalLayout_2.addLayout(self.verticalLayout_16)
        self.horizontalLayout_6.addWidget(self.widget_4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.sale_9 = QtWidgets.QLabel(parent=self.widget_3)
        self.sale_9.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sale_9.setFont(font)
        self.sale_9.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.sale_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sale_9.setObjectName("sale_9")
        self.horizontalLayout_5.addWidget(self.sale_9)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_5.setMinimumSize(QtCore.QSize(900, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(801, 171))
        self.widget_5.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.photo_9 = QtWidgets.QLabel(parent=self.widget_5)
        self.photo_9.setMaximumSize(QtCore.QSize(150, 150))
        self.photo_9.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.photo_9.setText("")
        self.photo_9.setPixmap(QtGui.QPixmap("../import/1.jpg"))
        self.photo_9.setScaledContents(True)
        self.photo_9.setObjectName("photo_9")
        self.horizontalLayout_8.addWidget(self.photo_9)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.label_25 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_17.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_17.addWidget(self.label_26)
        self.label_43 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_43.setObjectName("label_43")
        self.verticalLayout_17.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_44.setObjectName("label_44")
        self.verticalLayout_17.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_45.setObjectName("label_45")
        self.verticalLayout_17.addWidget(self.label_45)
        self.verticalLayout_3.addLayout(self.verticalLayout_17)
        self.horizontalLayout_8.addWidget(self.widget_6)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.sale_10 = QtWidgets.QLabel(parent=self.widget_5)
        self.sale_10.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sale_10.setFont(font)
        self.sale_10.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.sale_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sale_10.setObjectName("sale_10")
        self.horizontalLayout_7.addWidget(self.sale_10)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        List_of_products.setCentralWidget(self.centralwidget)

        self.retranslateUi(List_of_products)
        QtCore.QMetaObject.connectSlotsByName(List_of_products)

    def retranslateUi(self, List_of_products):
        _translate = QtCore.QCoreApplication.translate
        List_of_products.setWindowTitle(_translate("List_of_products", "MainWindow"))
        self.provider_input.setItemText(0, _translate("List_of_products", "Все поставщики"))
        self.sort_input.setCurrentText(_translate("List_of_products", "Без сортировки"))
        self.sort_input.setItemText(0, _translate("List_of_products", "Без сортировки"))
        self.sort_input.setItemText(1, _translate("List_of_products", "По возрастанию"))
        self.sort_input.setItemText(2, _translate("List_of_products", "По убыванию"))
        self.search_input.setPlaceholderText(_translate("List_of_products", "Поиск"))
        self.add_product_button.setText(_translate("List_of_products", "Добавить товар"))
        self.delete_product_button.setText(_translate("List_of_products", "Удалить товар"))
        self.order_button.setText(_translate("List_of_products", "Заказы"))
        self.user_fio.setText(_translate("List_of_products", "Фамилия Имя Отчество"))
        self.logout_button.setText(_translate("List_of_products", "Выход"))
        self.label_15.setText(_translate("List_of_products", "Категория товара| Наименование товара"))
        self.label_27.setText(_translate("List_of_products", "Описание товара:"))
        self.label_28.setText(_translate("List_of_products", "Производитель:"))
        self.label_46.setText(_translate("List_of_products", "Поставщик:"))
        self.label_47.setText(_translate("List_of_products", "Цена:"))
        self.label_48.setText(_translate("List_of_products", "Еденица измерения:"))
        self.sale_11.setText(_translate("List_of_products", "Действующая скидка"))
        self.label_12.setText(_translate("List_of_products", "Категория товара| Наименование товара"))
        self.label_21.setText(_translate("List_of_products", "Описание товара:"))
        self.label_22.setText(_translate("List_of_products", "Производитель:"))
        self.label_37.setText(_translate("List_of_products", "Поставщик:"))
        self.label_38.setText(_translate("List_of_products", "Цена:"))
        self.label_39.setText(_translate("List_of_products", "Еденица измерения:"))
        self.sale_8.setText(_translate("List_of_products", "Действующая скидка"))
        self.label_13.setText(_translate("List_of_products", "Категория товара| Наименование товара"))
        self.label_23.setText(_translate("List_of_products", "Описание товара:"))
        self.label_24.setText(_translate("List_of_products", "Производитель:"))
        self.label_40.setText(_translate("List_of_products", "Поставщик:"))
        self.label_41.setText(_translate("List_of_products", "Цена:"))
        self.label_42.setText(_translate("List_of_products", "Еденица измерения:"))
        self.sale_9.setText(_translate("List_of_products", "Действующая скидка"))
        self.label_14.setText(_translate("List_of_products", "Категория товара| Наименование товара"))
        self.label_25.setText(_translate("List_of_products", "Описание товара:"))
        self.label_26.setText(_translate("List_of_products", "Производитель:"))
        self.label_43.setText(_translate("List_of_products", "Поставщик:"))
        self.label_44.setText(_translate("List_of_products", "Цена:"))
        self.label_45.setText(_translate("List_of_products", "Еденица измерения:"))
        self.sale_10.setText(_translate("List_of_products", "Действующая скидка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    List_of_products = QtWidgets.QMainWindow()
    ui = Ui_List_of_products()
    ui.setupUi(List_of_products)
    List_of_products.show()
    sys.exit(app.exec())
