# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import QWidget


class CardUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(957, 300)
        self.widget_7 = QtWidgets.QWidget(parent=Form)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 995, 171))
        self.widget_7.setMinimumSize(QtCore.QSize(995, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(995, 300))
        self.widget_7.setStyleSheet("\n"
                                    "border: 1px solid black;\n"
                                    "")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.photo_10 = QtWidgets.QLabel(parent=self.widget_7)
        self.photo_10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo_10.sizePolicy().hasHeightForWidth())
        self.photo_10.setSizePolicy(sizePolicy)
        self.photo_10.setMaximumSize(QtCore.QSize(200, 200))
        self.photo_10.setStyleSheet("\n"
                                    "border: 1px solid black;\n"
                                    "")
        self.photo_10.setText("")
        self.photo_10.setPixmap(QtGui.QPixmap("res/1.jpg"))
        self.photo_10.setScaledContents(True)
        self.photo_10.setObjectName("photo_10")
        self.horizontalLayout_9.addWidget(self.photo_10)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("\n"
                                    "border: 0px solid black;\n"
                                    "")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_18.addWidget(self.label_15)
        self.label_27 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("\n"
                                    "border: 0px solid black;\n"
                                    "")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_18.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("\n"
                                    "border: 0px solid black;\n"
                                    "")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_18.addWidget(self.label_28)
        self.label_46 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("\n"
                                    "border: 0px solid black;\n"
                                    "")
        self.label_46.setObjectName("label_46")
        self.verticalLayout_18.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("\n"
                                    "border: 0px solid black;\n"
                                    "")
        self.label_47.setObjectName("label_47")
        self.verticalLayout_18.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("\n"
                                    "border: 0px solid black;\n"
                                    "")
        self.label_48.setObjectName("label_48")
        self.verticalLayout_18.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("\n"
                                    "border: 0px solid black;\n"
                                    "")
        self.label_49.setObjectName("label_49")
        self.verticalLayout_18.addWidget(self.label_49)
        self.verticalLayout_5.addLayout(self.verticalLayout_18)
        self.horizontalLayout_9.addWidget(self.widget_8)
        self.sale_11 = QtWidgets.QLabel(parent=self.widget_7)
        self.sale_11.setMaximumSize(QtCore.QSize(150, 200))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sale_11.setFont(font)
        self.sale_11.setStyleSheet("\n"
                                   "border: 1px solid black;\n"
                                   "")
        self.sale_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sale_11.setObjectName("sale_11")
        self.horizontalLayout_9.addWidget(self.sale_11)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_15.setText(_translate("Form", "Категория товара| Наименование товара"))
        self.label_27.setText(_translate("Form", "Описание товара:"))
        self.label_28.setText(_translate("Form", "Производитель:"))
        self.label_46.setText(_translate("Form", "Поставщик:"))
        self.label_47.setText(_translate("Form", "Цена:"))
        self.label_48.setText(_translate("Form", "Еденица измерения:"))
        self.label_49.setText(_translate("Form", "Количество на складе:"))
        self.sale_11.setText(_translate("Form", "Действующая скидка"))




class ProductCardUI(QWidget, CardUI):
    clicked = pyqtSignal(object)
    doubleClicked = pyqtSignal(object)

    def __init__(self, id, category, name, description, manufacturer, supplier, price, unit, quantity, discount_percent, image_path="picture.png"):
        super().__init__()

        self.category = category
        self.id = id

        self.name = name
        self.description = description
        self.manufacturer = manufacturer
        self.supplier = supplier
        self.price = price
        self.unit = unit
        self.quantity = quantity
        self.discount_percent = discount_percent
        self.image_path = image_path

        self.setupUi(self)
        self.product_name = name
        self.label_15.setText(name)
        self.label_27.setText(f"Описание товара: {description}")
        self.label_28.setText(f"Производитель: {manufacturer}")
        self.label_46.setText(f"Поставщик: {supplier}")

        if int(self.discount_percent) > 0:
            self.label_47.setText(f"Цена: <span style='text-decoration: line-through; color: #FF0000;'>{float(self.price):.2f}</span> <span>{float(self.price) * (100 - float(self.discount_percent)) / 100:.2f} руб. </span>")
        else:
            self.label_47.setText(f"Цена: <span>{float(self.price):.2f}</span>")

        self.label_48.setText(f"Еденица измерения: {unit}")
        self.label_49.setText(f"Количество на складе: {quantity}")
        self.sale_11.setText(f"Скидка: {discount_percent}%")

        self.photo_10.setText("")
        self.photo_10.setPixmap(QtGui.QPixmap(f"res/images/{image_path}"))
        self.photo_10.setScaledContents(True)
        self.photo_10.setObjectName("photo_10")

        self.setMaximumWidth(1031)
        self.setMinimumHeight(171)

        self.show()

    def mousePressEvent(self, event):
        self.clicked.emit(self)

    def mouseDoubleClickEvent(self, event):
        self.doubleClicked.emit(self)

    def set_selected(self, selected: bool):
        if selected:
            self.photo_10.setStyleSheet("border: 2px solid #00FA9A;")
            self.sale_11.setStyleSheet("border: 2px solid #00FA9A;")
            self.widget_7.setStyleSheet("border: 2px solid #00FA9A;")
        else:
            self.photo_10.setStyleSheet("border: 1px solid black;")
            self.sale_11.setStyleSheet("border: 1px solid black;")
            self.widget_7.setStyleSheet("border: 1px solid black;")

    def disconnect_all(self):
        try:
            self.clicked.disconnect()
        except:
            pass
        try:
            self.doubleClicked.disconnect()
        except:
            pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = ProductCardUI(
        name="Смартфон X300",
        description="Флагман",
        manufacturer="TechCorp",
        supplier="GlobalSupplies",
        price="70000",
        unit="шт.",
        discount_percent=5,
        image_path="../Desktop/import/1.jpg",
        quantity=1)
    sys.exit(app.exec())