# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget


class CardUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.widget_7 = QtWidgets.QWidget(parent=Form)
        self.widget_7.setMinimumSize(QtCore.QSize(900, 0))

        self.widget_7.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.photo_10 = QtWidgets.QLabel(parent=self.widget_7)
        self.photo_10.setMaximumSize(QtCore.QSize(150, 150))
        self.photo_10.setStyleSheet("\n"
"border: 1px solid black;\n"
"")

        self.horizontalLayout_11.addWidget(self.photo_10)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_18.addWidget(self.label_15)
        self.label_27 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_18.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_18.addWidget(self.label_28)
        self.label_46 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_46.setObjectName("label_46")
        self.verticalLayout_18.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_47.setObjectName("label_47")
        self.verticalLayout_18.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("\n"
"border: 0px solid black;\n"
"")
        self.label_48.setObjectName("label_48")
        self.verticalLayout_18.addWidget(self.label_48)

        self.label_49 = QtWidgets.QLabel(parent=self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("\n"
                                    "border: 0px solid black;\n"
                                    "")
        self.label_49.setObjectName("label_47")
        self.verticalLayout_18.addWidget(self.label_49)

        self.verticalLayout_5.addLayout(self.verticalLayout_18)
        self.horizontalLayout_11.addWidget(self.widget_8)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.sale_11 = QtWidgets.QLabel(parent=self.widget_7)
        self.sale_11.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sale_11.setFont(font)
        self.sale_11.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.sale_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sale_11.setObjectName("sale_11")
        self.horizontalLayout_9.addWidget(self.sale_11)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_15.setText(_translate("Form", "Категория товара| Наименование товара"))
        self.label_27.setText(_translate("Form", "Описание товара:"))
        self.label_28.setText(_translate("Form", "Производитель:"))
        self.label_46.setText(_translate("Form", "Поставщик:"))
        self.label_47.setText(_translate("Form", "Цена:"))
        self.label_48.setText(_translate("Form", "Еденица измерения:"))
        self.label_49.setText(_translate("Form", "Количество на складе:"))
        self.sale_11.setText(_translate("Form", "Действующая скидка"))
        self.photo_10.setText("")
        self.photo_10.setPixmap(QtGui.QPixmap(f"res/icon.jpg"))
        self.photo_10.setScaledContents(True)
        self.photo_10.setObjectName("photo_10")




class ProductCardUI(QWidget, CardUI):
    def __init__(self, name, description, manufacturer, supplier, price, unit, quantity, discount_percent, image_path="picture.png"):
        super().__init__()
        self.setupUi(self)
        self.label_15.setText(name)
        self.label_27.setText(f"Описание товара: {description}")
        self.label_28.setText(f"Производитель: {manufacturer}")
        self.label_46.setText(f"Поставщик: {supplier}")
        self.label_47.setText(f"Цена: <span style='text-decoration: line-through; color: #FF0000;'>{price}</span> <span>{int(price) * (100-int(discount_percent))/100} руб. </span>")
        self.label_48.setText(f"Еденица измерения: {unit}")
        self.label_49.setText(f"Количество на складе: {quantity}")
        self.sale_11.setText(f"Скидка: {discount_percent}%")

        self.photo_10.setText("")
        self.photo_10.setPixmap(QtGui.QPixmap(f"res/{image_path}"))
        self.photo_10.setScaledContents(True)
        self.photo_10.setObjectName("photo_10")

        self.setMinimumHeight(170)


        self.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = ProductCardUI(
        name="Смартфон X300",
        description="Флагман",
        manufacturer="TechCorp",
        supplier="GlobalSupplies",
        price="70000 руб.",
        unit="шт.",
        discount_percent=5,
        image_path="../Desktop/import/1.jpg",
        quantity=1)
    sys.exit(app.exec())