# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'products.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_List_of_products(object):
    def setupUi(self, List_of_products):
        List_of_products.setObjectName("List_of_products")
        List_of_products.resize(1067, 544)
        List_of_products.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(List_of_products)
        self.centralwidget.setObjectName("centralwidget")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(10, 10, 71, 61))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("../import/Icon.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 150, 901, 304))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.photo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.photo.setMaximumSize(QtCore.QSize(300, 300))
        self.photo.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../import/1.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.horizontalLayout_9.addWidget(self.photo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.sale = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.sale.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sale.setFont(font)
        self.sale.setStyleSheet("\n"
"border: 1px solid black;\n"
"")
        self.sale.setObjectName("sale")
        self.horizontalLayout_9.addWidget(self.sale)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 0, 921, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.provider_input = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.provider_input.setFont(font)
        self.provider_input.setStyleSheet("#provider_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#provider_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.provider_input.setObjectName("provider_input")
        self.provider_input.addItem("")
        self.horizontalLayout_3.addWidget(self.provider_input)
        self.sort_input = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sort_input.setFont(font)
        self.sort_input.setStyleSheet("#sort_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#sort_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.sort_input.setObjectName("sort_input")
        self.sort_input.addItem("")
        self.sort_input.addItem("")
        self.sort_input.addItem("")
        self.horizontalLayout_3.addWidget(self.sort_input)
        self.search_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.search_input.setFont(font)
        self.search_input.setStyleSheet("#search_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#search_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.search_input.setText("")
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_3.addWidget(self.search_input)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.add_product_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.add_product_button.setMinimumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.add_product_button.setFont(font)
        self.add_product_button.setStyleSheet("#add_product_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#add_product_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.add_product_button.setObjectName("add_product_button")
        self.horizontalLayout_10.addWidget(self.add_product_button)
        self.delete_product_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delete_product_button.setMinimumSize(QtCore.QSize(85, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.delete_product_button.setFont(font)
        self.delete_product_button.setStyleSheet("#delete_product_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#delete_product_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.delete_product_button.setObjectName("delete_product_button")
        self.horizontalLayout_10.addWidget(self.delete_product_button)
        self.order_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.order_button.setMinimumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.order_button.setFont(font)
        self.order_button.setStyleSheet("#order_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#order_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.order_button.setObjectName("order_button")
        self.horizontalLayout_10.addWidget(self.order_button)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_fio = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.user_fio.setFont(font)
        self.user_fio.setObjectName("user_fio")
        self.horizontalLayout.addWidget(self.user_fio)
        self.logout_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.logout_button.setMinimumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("#logout_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#logout_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout.addWidget(self.logout_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(960, 470, 91, 61))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 95, 188))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        List_of_products.setCentralWidget(self.centralwidget)

        self.retranslateUi(List_of_products)
        QtCore.QMetaObject.connectSlotsByName(List_of_products)

    def retranslateUi(self, List_of_products):
        _translate = QtCore.QCoreApplication.translate
        List_of_products.setWindowTitle(_translate("List_of_products", "MainWindow"))
        self.label_2.setText(_translate("List_of_products", "Категория товара| Наименование товара"))
        self.label_3.setText(_translate("List_of_products", "Описание товара:"))
        self.label_7.setText(_translate("List_of_products", "Производитель:"))
        self.label_11.setText(_translate("List_of_products", "Поставщик:"))
        self.label_13.setText(_translate("List_of_products", "Цена:"))
        self.label_15.setText(_translate("List_of_products", "Еденица измерения:"))
        self.label_17.setText(_translate("List_of_products", "Количество на складе:"))
        self.sale.setText(_translate("List_of_products", "Действующая скидка"))
        self.provider_input.setItemText(0, _translate("List_of_products", "Все поставщики"))
        self.sort_input.setCurrentText(_translate("List_of_products", "Без сортировки"))
        self.sort_input.setItemText(0, _translate("List_of_products", "Без сортировки"))
        self.sort_input.setItemText(1, _translate("List_of_products", "По возрастанию"))
        self.sort_input.setItemText(2, _translate("List_of_products", "По убыванию"))
        self.search_input.setPlaceholderText(_translate("List_of_products", "Поиск"))
        self.add_product_button.setText(_translate("List_of_products", "Добавить товар"))
        self.delete_product_button.setText(_translate("List_of_products", "Удалить товар"))
        self.order_button.setText(_translate("List_of_products", "Заказы"))
        self.user_fio.setText(_translate("List_of_products", "Фамилия Имя Отчество"))
        self.logout_button.setText(_translate("List_of_products", "Выход"))
        self.pushButton_6.setText(_translate("List_of_products", "PushButton"))
        self.pushButton_3.setText(_translate("List_of_products", "PushButton"))
        self.pushButton_4.setText(_translate("List_of_products", "PushButton"))
        self.pushButton_5.setText(_translate("List_of_products", "PushButton"))
        self.pushButton_7.setText(_translate("List_of_products", "PushButton"))
        self.pushButton_2.setText(_translate("List_of_products", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    List_of_products = QtWidgets.QMainWindow()
    ui = Ui_List_of_products()
    ui.setupUi(List_of_products)
    List_of_products.show()
    sys.exit(app.exec_())
