# Form implementation generated from reading ui file 'order_list_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(569, 618)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.order_button_back = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.order_button_back.setFont(font)
        self.order_button_back.setStyleSheet("QPushButton#order_button_back {\n"
"    background-color: #7FFF00;\n"
"}\n"
"\n"
"QPushButton#order_button_back:hover {\n"
"    background-color: #00FA9A; \n"
"}\n"
"")
        self.order_button_back.setObjectName("order_button_back")
        self.horizontalLayout.addWidget(self.order_button_back)
        spacerItem = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)

        self.window_name_label = QtWidgets.QLabel()
        self.window_name_label.setText("Заказы")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.window_name_label.setFont(font)

        self.horizontalLayout.addWidget(self.window_name_label)


        self.horizontalLayout.addItem(spacerItem)
        self.order_button_add = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.order_button_add.setFont(font)
        self.order_button_add.setStyleSheet("QPushButton#order_button_add {\n"
"    background-color: #7FFF00;\n"
"}\n"
"\n"
"QPushButton#order_button_add:hover {\n"
"    background-color: #00FA9A; \n"
"}\n"
"")
        self.order_button_add.setObjectName("order_button_add")
        self.horizontalLayout.addWidget(self.order_button_add)
        self.order_button_remove = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.order_button_remove.setFont(font)
        self.order_button_remove.setStyleSheet("QPushButton#order_button_remove {\n"
"    background-color: #7FFF00;\n"
"}\n"
"\n"
"QPushButton#order_button_remove:hover {\n"
"    background-color: #00FA9A; \n"
"}\n"
"")
        self.order_button_remove.setObjectName("order_button_remove")
        self.horizontalLayout.addWidget(self.order_button_remove)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 545, 563))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.order_button_back.setText(_translate("Dialog", " Назад к товарам "))
        self.order_button_add.setText(_translate("Dialog", " Добавить заказ "))
        self.order_button_remove.setText(_translate("Dialog", " Удалить заказ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
