# Form implementation generated from reading ui file 'order_data.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import QWidget


class Order_widget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        #новое
        self.widget_order = QtWidgets.QWidget(parent=Form)
        layout = QtWidgets.QVBoxLayout(Form)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.widget_order)

        # self.widget_order = QtWidgets.QWidget(parent=Form)
        # #self.widget_order.setGeometry(QtCore.QRect(0, 0, 525, 118))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_order.sizePolicy().hasHeightForWidth())
        self.widget_order.setSizePolicy(sizePolicy)
        self.widget_order.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_order.setMinimumSize(QtCore.QSize(525, 118))
        self.widget_order.setStyleSheet("QWidget#widget_order {\n"
                                        "    border: 1px solid #000; \n"
                                        "}\n" )
        self.widget_order.setObjectName("widget_order")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_order)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_order_name = QtWidgets.QWidget(parent=self.widget_order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_order_name.sizePolicy().hasHeightForWidth())
        self.widget_order_name.setSizePolicy(sizePolicy)
        self.widget_order_name.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.widget_order_name.setFont(font)
        self.widget_order_name.setStyleSheet("QWidget#widget_order_name {\n"
"    border: 1px solid #000; \n"
"}")
        self.widget_order_name.setObjectName("widget_order_name")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_order_name)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_art = QtWidgets.QLabel(parent=self.widget_order_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_art.sizePolicy().hasHeightForWidth())
        self.label_art.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        self.label_art.setFont(font)
        self.label_art.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.label_art.setObjectName("label_art")
        self.verticalLayout_4.addWidget(self.label_art)
        self.label_status = QtWidgets.QLabel(parent=self.widget_order_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_4.addWidget(self.label_status)
        self.label_adress = QtWidgets.QLabel(parent=self.widget_order_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_adress.sizePolicy().hasHeightForWidth())
        self.label_adress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_adress.setFont(font)
        self.label_adress.setObjectName("label_adress")
        self.verticalLayout_4.addWidget(self.label_adress)
        self.label_order_date = QtWidgets.QLabel(parent=self.widget_order_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_order_date.sizePolicy().hasHeightForWidth())
        self.label_order_date.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_order_date.setFont(font)
        self.label_order_date.setObjectName("label_order_date")
        self.verticalLayout_4.addWidget(self.label_order_date)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addWidget(self.widget_order_name)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_delivery_date = QtWidgets.QLabel(parent=self.widget_order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_delivery_date.sizePolicy().hasHeightForWidth())
        self.label_delivery_date.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_delivery_date.setFont(font)
        self.label_delivery_date.setStyleSheet("border: 1px solid black;")
        self.label_delivery_date.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_delivery_date.setLineWidth(0)
        self.label_delivery_date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_delivery_date.setObjectName("label_delivery_date")
        self.horizontalLayout_2.addWidget(self.label_delivery_date)

        self.label_adress.setStyleSheet("border: 0px solid;")
        self.label_art.setStyleSheet("border: 0px solid;")
        self.label_order_date.setStyleSheet("border: 0px solid;")
        self.label_status.setStyleSheet("border: 0px solid;")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_art.setText(_translate("Form", "Артикул заказа"))
        self.label_status.setText(_translate("Form", "Статус заказа"))
        self.label_adress.setText(_translate("Form", "Адрес пункта выдачи"))
        self.label_order_date.setText(_translate("Form", "Дата заказа"))
        self.label_delivery_date.setText(_translate("Form", "Дата доставки"))

class OrderDataWidget(QWidget, Order_widget):
    clicked = pyqtSignal(object)
    doubleClicked = pyqtSignal(object)
    def __init__(self, id, status, address, order_date, delivery_date, quantity, username, product_id, user_id):
        super().__init__()
        self.id = id
        self.status = status
        self.address = address
        self.order_date = order_date
        self.delivery_date = delivery_date
        self.quantity = quantity
        self.username = username
        self.user_id = user_id
        self.product_id = product_id

        self.setupUi(self)

        self.label_art.setText(f"Артикул заказа: {self.id}")
        self.label_status.setText(f"Статус заказа: {self.status}")
        self.label_adress.setText(f"Адрес пункта выдачи: {self.address}")
        self.label_order_date.setText(f"Дата заказа: {self.order_date}")
        self.label_delivery_date.setText(f"Дата доставки:\n{self.delivery_date}")

    def mousePressEvent(self, event):
        self.clicked.emit(self)

    def mouseDoubleClickEvent(self, event):
        self.doubleClicked.emit(self)


    def set_selected(self, selected: bool):
        if selected:
            self.widget_order.setStyleSheet("border: 2px solid #00FA9A;")
        else:
            self.widget_order.setStyleSheet("border: 1px solid black;")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Order_widget()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
