# Form implementation generated from reading ui file 'product_edit_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from unicodedata import category

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_windowTitle(object):
    def setupUi(self, windowTitle):
        windowTitle.setObjectName("windowTitle")
        windowTitle.resize(542, 737)
        self.gridLayout_2 = QtWidgets.QGridLayout(windowTitle)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 24, 0, 1, 1)
        self.description_input = QtWidgets.QTextEdit(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.description_input.setFont(font)
        self.description_input.setStyleSheet("#description_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#description_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.description_input.setObjectName("description_input")
        self.gridLayout_2.addWidget(self.description_input, 13, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 14, 0, 1, 1)
        self.discount_input = QtWidgets.QSpinBox(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.discount_input.setFont(font)
        self.discount_input.setStyleSheet("#discount_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#discount_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.discount_input.setMaximum(100)
        self.discount_input.setObjectName("discount_input")
        self.gridLayout_2.addWidget(self.discount_input, 25, 0, 1, 1)
        self.photo = QtWidgets.QLabel(parent=windowTitle)
        self.photo.setMaximumSize(QtCore.QSize(70, 70))
        self.photo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../import/picture.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.gridLayout_2.addWidget(self.photo, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 1)
        self.name_input = QtWidgets.QLineEdit(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.name_input.setFont(font)
        self.name_input.setStyleSheet("#name_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#name_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.name_input.setPlaceholderText("")
        self.name_input.setObjectName("name_input")
        self.gridLayout_2.addWidget(self.name_input, 9, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(parent=windowTitle)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("#cancel_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#cancel_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout_2.addWidget(self.cancel_button, 28, 0, 1, 1)
        self.price_input = QtWidgets.QDoubleSpinBox(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.price_input.setFont(font)
        self.price_input.setStyleSheet("#price_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#price_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.price_input.setMinimum(0.0)
        self.price_input.setMaximum(1e+26)
        self.price_input.setObjectName("price_input")
        self.gridLayout_2.addWidget(self.price_input, 19, 0, 1, 1)
        self.quantity_input = QtWidgets.QSpinBox(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.quantity_input.setFont(font)
        self.quantity_input.setStyleSheet("#quantity_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#quantity_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.quantity_input.setSuffix("")
        self.quantity_input.setMaximum(1000000000)
        self.quantity_input.setObjectName("quantity_input")
        self.gridLayout_2.addWidget(self.quantity_input, 23, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 10, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=windowTitle)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 26, 0, 1, 1)
        self.metric_input = QtWidgets.QLineEdit(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.metric_input.setFont(font)
        self.metric_input.setStyleSheet("#metric_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#metric_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.metric_input.setObjectName("metric_input")
        self.gridLayout_2.addWidget(self.metric_input, 21, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(parent=windowTitle)
        self.save_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("#save_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#save_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.save_button.setObjectName("save_button")
        self.gridLayout_2.addWidget(self.save_button, 27, 0, 1, 1)
        self.provider_input = QtWidgets.QLineEdit(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.provider_input.setFont(font)
        self.provider_input.setStyleSheet("#provider_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#provider_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.provider_input.setObjectName("provider_input")
        self.gridLayout_2.addWidget(self.provider_input, 17, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 12, 0, 1, 1)
        self.download_photo = QtWidgets.QPushButton(parent=windowTitle)
        self.download_photo.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.download_photo.setFont(font)
        self.download_photo.setStyleSheet("#download_photo {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#download_photo:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.download_photo.setObjectName("download_photo")
        self.gridLayout_2.addWidget(self.download_photo, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 20, 0, 1, 1)
        self.maker_input = QtWidgets.QComboBox(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.maker_input.setFont(font)
        self.maker_input.setStyleSheet("#maker_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#maker_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.maker_input.setObjectName("maker_input")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.gridLayout_2.addWidget(self.maker_input, 15, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 18, 0, 1, 1)
        self.category_input = QtWidgets.QComboBox(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.category_input.setFont(font)
        self.category_input.setStyleSheet("#category_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#category_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.category_input.setObjectName("category_input")
        self.category_input.addItem("")
        self.category_input.addItem("")
        self.category_input.addItem("")
        self.gridLayout_2.addWidget(self.category_input, 11, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 16, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=windowTitle)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 22, 0, 1, 1)

        self.retranslateUi(windowTitle)
        QtCore.QMetaObject.connectSlotsByName(windowTitle)

    def retranslateUi(self, windowTitle):
        _translate = QtCore.QCoreApplication.translate
        windowTitle.setWindowTitle(_translate("windowTitle", "Dialog"))
        self.label_12.setText(_translate("windowTitle", "Скидка (%):"))
        self.label_7.setText(_translate("windowTitle", "Производитель:"))
        self.label_4.setText(_translate("windowTitle", "Наименование:"))
        self.cancel_button.setText(_translate("windowTitle", "Отмена"))
        self.label_5.setText(_translate("windowTitle", "Категория:"))
        self.save_button.setText(_translate("windowTitle", "Сохранить"))
        self.label_6.setText(_translate("windowTitle", "Описание:"))
        self.download_photo.setText(_translate("windowTitle", "Загрузить фото"))
        self.label.setText(_translate("windowTitle", "Фото:"))
        self.label_10.setText(_translate("windowTitle", "Ед. измерения:"))
        self.maker_input.setItemText(0, _translate("windowTitle", "Производитель не выбран"))
        self.maker_input.setItemText(1, _translate("windowTitle", "Kari"))
        self.maker_input.setItemText(2, _translate("windowTitle", "Marco Tozzi"))
        self.maker_input.setItemText(3, _translate("windowTitle", "Рос"))
        self.maker_input.setItemText(4, _translate("windowTitle", "Rieker"))
        self.maker_input.setItemText(5, _translate("windowTitle", "Alessio Nesca"))
        self.maker_input.setItemText(6, _translate("windowTitle", "CROSBY"))
        self.label_9.setText(_translate("windowTitle", "Цена"))
        self.category_input.setItemText(0, _translate("windowTitle", "Категория не выбрана"))
        self.category_input.setItemText(1, _translate("windowTitle", "Женская обувь"))
        self.category_input.setItemText(2, _translate("windowTitle", "Мужская обувь"))
        self.label_8.setText(_translate("windowTitle", "Поставщик:"))
        self.label_11.setText(_translate("windowTitle", "Количество:"))


class product_edit_window(QDialog, Ui_windowTitle):
    def __init__(self, update_list):
        super().__init__()
        self.setupUi(self)
        self.update_list = update_list

    def setData(
            self,
            db,
            id,
            category,
            name,
            manufacturer,
            description,
            supplier,
            price,
            unit,
            quantity,
            discount_percent,
            image_path
            ):

        self.id = id
        self.db = db
        self.category = category
        self.name = name
        self.manufacturer = manufacturer
        self.description = description
        self.supplier = supplier
        self.price = price
        self.unit = unit
        self.quantity = quantity
        self.discount_percent = discount_percent
        self.image_path = image_path

        self.photo.setPixmap(QtGui.QPixmap(f"res/{image_path}"))
        self.name_input.setText(name)
        self.maker_input.setCurrentText(manufacturer)
        self.description_input.setText(description)
        self.category_input.setCurrentText(category)
        self.provider_input.setText(supplier)
        self.price_input.setValue(float(price))
        self.metric_input.setText(unit)
        self.quantity_input.setValue(int(quantity))
        self.discount_input.setValue(int(discount_percent))

    def connect_signals(self):
        self.save_button.clicked.connect(self.save_to_db)
        self.save_button.clicked.connect(self.accept)
        self.cancel_button.clicked.connect(self.close)

    def save_to_db(self):
        query = """
            UPDATE products SET
                сategory = %s,
                name = %s,
                manufacturer = %s,
                description = %s,
                supplier = %s,
                price = %s,
                unit_of_measurement = %s,
                quantity = %s,
                discount = %s,
                photo = %s
            WHERE product_id = %s;
        """
        params = (
            self.category_input.currentText(),
            self.name_input.text(),
            self.maker_input.currentText(),
            self.description_input.toPlainText(),
            self.provider_input.text(),
            self.price_input.value(),
            self.metric_input.text(),
            self.quantity_input.value(),
            self.discount_input.value(),
            self.image_path,
            self.id
        )
        try:
            result = self.db.execute_query(query, params, fetch=False)
            if not result:
                print("Ошибка добавления.")

        except Exception as e:
            print(f"Ошибка добавления: {e}")




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowTitle = QtWidgets.QDialog()
    ui = Ui_windowTitle()
    ui.setupUi(windowTitle)
    windowTitle.show()
    sys.exit(app.exec())
