# Form implementation generated from reading ui file 'order_list_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_order_list(object):
    def setupUi(self, order_list):
        order_list.setObjectName("order_list")
        order_list.resize(387, 432)
        self.centralwidget = QtWidgets.QWidget(parent=order_list)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        order_list.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=order_list)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 21))
        self.menubar.setObjectName("menubar")
        order_list.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=order_list)
        self.statusbar.setObjectName("statusbar")
        order_list.setStatusBar(self.statusbar)

        self.retranslateUi(order_list)
        QtCore.QMetaObject.connectSlotsByName(order_list)

    def retranslateUi(self, order_list):
        _translate = QtCore.QCoreApplication.translate
        order_list.setWindowTitle(_translate("order_list", "MainWindow"))
        self.pushButton.setText(_translate("order_list", "Назад к товарам"))
        self.pushButton_2.setText(_translate("order_list", "Добавить заказ"))
        self.pushButton_3.setText(_translate("order_list", "Удалить заказ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    order_list = QtWidgets.QMainWindow()
    ui = Ui_order_list()
    ui.setupUi(order_list)
    order_list.show()
    sys.exit(app.exec())
