# Form implementation generated from reading ui file 'order_edit_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_order_edit(object):
    def setupUi(self, order_edit):
        order_edit.setObjectName("order_edit")
        order_edit.resize(434, 523)
        self.gridLayout_2 = QtWidgets.QGridLayout(order_edit)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=order_edit)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=order_edit)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setCalendarPopup(False)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 9, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(parent=order_edit)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=order_edit)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=order_edit)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=order_edit)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=order_edit)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 3, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(parent=order_edit)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=order_edit)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=order_edit)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=order_edit)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=order_edit)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(order_edit)
        QtCore.QMetaObject.connectSlotsByName(order_edit)

    def retranslateUi(self, order_edit):
        _translate = QtCore.QCoreApplication.translate
        order_edit.setWindowTitle(_translate("order_edit", "Dialog"))
        self.dateEdit_2.setDisplayFormat(_translate("order_edit", "dd.MM.yyyy"))
        self.label_3.setText(_translate("order_edit", "Адрес ПВЗ:"))
        self.label_2.setText(_translate("order_edit", "Статус заказа:"))
        self.label.setText(_translate("order_edit", "Артикул заказа:"))
        self.label_5.setText(_translate("order_edit", "Дата доставки:"))
        self.label_4.setText(_translate("order_edit", "Дата заказа:"))
        self.pushButton.setText(_translate("order_edit", "Сохранить"))
        self.pushButton_2.setText(_translate("order_edit", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    order_edit = QtWidgets.QDialog()
    ui = Ui_order_edit()
    ui.setupUi(order_edit)
    order_edit.show()
    sys.exit(app.exec())
